# .github/workflows/tests.yml
name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: {}

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]   # add macos-latest if you want
        python-version: [ "3.10", "3.11", "3.12" ]

    env:
      PYTHONUTF8: "1"  # stable UTF-8 across OSes

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            pyproject.toml
            requirements*.txt

      # Optional: ensure UTF-8 console on Windows (helps with Greek text)
      - name: Ensure UTF-8 codepage (Windows)
        if: runner.os == 'Windows'
        run: chcp 65001
        shell: cmd

      - name: Install
        run: |
          python -m pip install -U pip
          pip install ".[dev]" || pip install .

      - name: Lint (ruff)
        run: ruff check .

      - name: Format check (black)
        run: black --check .

      - name: Type check (mypy)
        run: |
          mypy --version
          mypy src --config-file pyproject.toml --pretty --show-error-codes

      - name: Tests
        run: pytest -q
